<h1><?= $this->translate('New SSH Access'); ?></h1>

<div class="uk-grid">
    <div class="uk-width-medium-1-1 uk-grid-margin">
        <div class="md-card">
            <div class="md-card-toolbar">
                <h3 class="md-card-toolbar-heading-text">
                    <?= $this->translate('SSH Access'); ?>
                </h3>
            </div>
            <div class="md-card-content">
                <?= $this->form()->openTag($this->form); ?>
                <?PHP $fieldset = $this->form->getBaseFieldset();
                $fieldsetName = $fieldset->getAttribute('name'); ?>
                <div class="uk-grid">
                    <div class="uk-width-1-1">


                        <div class="uk-form-row">
                            <?php
                            $elementName = 'sshPublicKey';
                            $element = $fieldset->get($elementName);
                            $element
                                ->setAttribute('id', 'elm-' . $fieldsetName . '-' . $elementName)
                                ->setAttribute('name', $fieldsetName . '[' . $elementName . ']')
                                ->setAttribute('class', 'md-input')
                                ->setAttribute('tabindex', 1)
                                ->setAttribute('autofocus', 'on')
                                ->setAttribute('autocomplete', 'off');
                            ?>
                            <?= $this->formLabel($element); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>

                        <div class="uk-form-row">
                            <?php
                            $elementName = 'host';
                            $element = $fieldset->get($elementName);
                            $element
                                ->setAttribute('id', 'elm-' . $fieldsetName . '-' . $elementName)
                                ->setAttribute('name', $fieldsetName . '[' . $elementName . ']')
                                ->setAttribute('class', 'md-input')
                                ->setAttribute('tabindex', 1)
                                ->setAttribute('autofocus', 'on')
                                ->setAttribute('autocomplete', 'off');
                            ?>
                            <?= $this->formLabel($element); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>

                        <div class="uk-form-row">
                            <?php
                            $elementName = 'userOnHost';
                            $element = $fieldset->get($elementName);
                            $element
                                ->setAttribute('id', 'elm-' . $fieldsetName . '-' . $elementName)
                                ->setAttribute('name', $fieldsetName . '[' . $elementName . ']')
                                ->setAttribute('class', 'md-input')
                                ->setAttribute('tabindex', 1)
                                ->setAttribute('autofocus', 'on')
                                ->setAttribute('autocomplete', 'off');
                            ?>
                            <?= $this->formLabel($element); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>

                        <div class="uk-form-row">
                            <?php
                            $elementName = 'doNotBlockIfUnused';
                            $element = $fieldset->get($elementName);
                            $element
                                ->setAttribute('id', 'elm-' . $fieldsetName . '-' . $elementName)
                                ->setAttribute('name', $fieldsetName . '[' . $elementName . ']')
                                ->setAttribute('class', 'md-input')
                                ->setAttribute('tabindex', 1)
                                ->setAttribute('autofocus', 'on')
                                ->setAttribute('autocomplete', 'off');
                            ?>
                            <?= $this->formLabel($element); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>

                        <div class="uk-form-row" style="text-align: right">
                            <?= $this->formElement($this->form->get($fieldsetName . '_csrf')); ?>
                            <?php
                            $this->form->get('submit')
                                ->setAttribute('id', 'submit')
                                ->setAttribute('class', 'md-btn md-btn-primary');
                            ?>
                            <?= $this->formElement($this->form->get('submit')); ?>
                        </div>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(function() {
        $('#elm-<?= $fieldsetName ?>-tags').selectize({
            plugins: {
                'remove_button': {
                    label: ''
                }
            },
            onDropdownOpen: function($dropdown) {
                $dropdown
                    .hide()
                    .velocity('slideDown', {
                        begin: function() {
                            $dropdown.css({
                                'margin-top': '0'
                            })
                        },
                        duration: 200,
                        easing: easing_swiftOut
                    })
            },
            onDropdownClose: function($dropdown) {
                $dropdown
                    .show()
                    .velocity('slideUp', {
                        complete: function() {
                            $dropdown.css({
                                'margin-top': ''
                            })
                        },
                        duration: 200,
                        easing: easing_swiftOut
                    })
            }
        });
    });
</script>