/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;

LOCK TABLES `LaminasSystemServerComposerOutdated` WRITE;
/*!40000 ALTER TABLE `LaminasSystemServerComposerOutdated` DISABLE KEYS */;
INSERT INTO `LaminasSystemServerComposerOutdated` VALUES
(161,'behat/transliterator','1.5.0','1.5.0','up-to-date','String transliterator',1,286),
(162,'brick/math','0.12.3','0.13.1','update-possible','Arbitrary-precision arithmetic library',1,287),
(163,'brick/varexporter','0.5.0','0.6.0','update-possible','A powerful alternative to var_export(), which can export closures and objects without __set_state()',1,288),
(164,'composer/semver','3.4.3','3.4.4','semver-safe-update','Semver library that offers utilities, version constraint parsing and validation.',1,296),
(165,'doctrine/annotations','2.0.2','2.0.2','up-to-date','Docblock Annotations Parser',1,298),
(166,'doctrine/cache','2.2.0','2.2.0','up-to-date','PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.',1,299),
(167,'doctrine/dbal','3.9.4','4.2.5','update-possible','Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.',1,302),
(168,'doctrine/inflector','2.0.10','2.1.0','semver-safe-update','PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.',1,308),
(169,'doctrine/lexer','2.1.1','3.0.1','update-possible','PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.',1,310),
(170,'doctrine/migrations','3.9.0','3.9.4','semver-safe-update','PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes to it. It is a very easy to use and a powerful tool.',1,311),
(171,'doctrine/orm','2.20.2','3.5.3','update-possible','Object-Relational-Mapper for PHP',1,312),
(172,'doctrine/persistence','3.4.0','4.1.1','update-possible','The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.',1,313),
(173,'egulias/email-validator','3.2.6','4.0.4','update-possible','A library for validating emails against several RFCs',1,315),
(174,'ezyang/htmlpurifier','4.18.0','4.19.0','semver-safe-update','Standards compliant HTML filter written in PHP',1,316),
(175,'gedmo/doctrine-extensions','3.20.0','3.21.0','semver-safe-update','Doctrine behavioral extensions',1,318),
(176,'guzzlehttp/guzzle','7.9.3','7.10.0','semver-safe-update','Guzzle is a PHP HTTP client library',1,319),
(177,'guzzlehttp/promises','2.2.0','2.3.0','semver-safe-update','Guzzle promises library',1,320),
(178,'guzzlehttp/psr7','2.7.1','2.8.0','semver-safe-update','PSR-7 message implementation that also provides common utility methods',1,321),
(179,'kint-php/kint','5.1.1','6.0.1','update-possible','Kint - debugging tool for PHP developers',1,322),
(180,'laminas/laminas-cache','3.13.0','4.1.0','update-possible','Caching implementation with a variety of storage options, as well as codified caching strategies for callbacks, classes, and output',1,324),
(181,'laminas/laminas-cache-storage-adapter-filesystem','2.5.0','3.1.0','update-possible','Laminas cache adapter for filesystem',1,325),
(182,'laminas/laminas-cache-storage-adapter-memory','2.4.0','3.1.0','update-possible','Laminas cache adapter for memory',1,326),
(183,'laminas/laminas-component-installer','3.5.0','3.6.0','semver-safe-update','Composer plugin for injecting modules and configuration providers into application configuration',1,330),
(184,'laminas/laminas-config','3.10.1','3.10.1','up-to-date','provides a nested object property based user interface for accessing this configuration data within application code',1,331),
(185,'laminas/laminas-development-mode','3.13.0','3.14.0','semver-safe-update','Laminas development mode script',1,335),
(186,'laminas/laminas-escaper','2.16.0','2.17.0','semver-safe-update','Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs',1,336),
(187,'laminas/laminas-filter','2.40.0','3.2.1','update-possible','Programmatically filter and normalize data and files',1,338),
(188,'laminas/laminas-http','2.21.0','2.22.0','semver-safe-update','Provides an easy interface for performing Hyper-Text Transfer Protocol (HTTP) requests',1,340),
(189,'laminas/laminas-i18n-resources','2.11.0','2.12.0','semver-safe-update','Provides validator and captcha translations for laminas-i18n\'s Translator',1,343),
(190,'laminas/laminas-inputfilter','2.32.0','2.33.1','semver-safe-update','Normalize and validate input sets from the web, APIs, the CLI, and more, including files',1,344),
(191,'laminas/laminas-json','3.7.1','3.7.1','up-to-date','provides convenience methods for serializing native PHP to JSON and decoding JSON to native PHP',1,345),
(192,'laminas/laminas-loader','2.11.1','2.11.1','up-to-date','Autoloading and plugin loading strategies',1,346),
(193,'laminas/laminas-mail','2.25.1','2.25.1','up-to-date','Provides generalized functionality to compose and send both text and MIME-compliant multipart e-mail messages',1,347),
(194,'laminas/laminas-mime','2.12.0','2.12.0','up-to-date','Create and parse MIME messages and parts',1,348),
(195,'laminas/laminas-modulemanager','2.17.0','2.18.0','semver-safe-update','Modular application system for laminas-mvc applications',1,349),
(196,'laminas/laminas-navigation','2.20.0','2.21.0','semver-safe-update','Manage trees of pointers to web pages in order to build navigation systems',1,354),
(197,'laminas/laminas-paginator','2.19.0','2.20.0','semver-safe-update','Paginate collections of data from arbitrary sources',1,355),
(198,'laminas/laminas-serializer','2.18.0','3.1.0','update-possible','Serialize and deserialize PHP structures to a variety of representations',1,358),
(199,'laminas/laminas-servicemanager','3.23.0','4.4.0','update-possible','Factory-Driven Dependency Injection Container',1,359),
(200,'laminas/laminas-session','2.24.0','2.25.1','semver-safe-update','Object-oriented interface to PHP sessions and storage',1,360),
(201,'laminas/laminas-text','2.12.1','2.12.1','up-to-date','Create FIGlets and text-based tables',1,363),
(202,'laminas/laminas-validator','2.64.2','3.8.0','update-possible','Validation classes for a wide range of domains, and the ability to chain validators to create complex validation criteria',1,366),
(203,'laminas/laminas-view','2.36.0','2.43.0','semver-safe-update','Flexible view layer supporting and providing multiple view layers, helpers, and more',1,367),
(204,'laminas/laminas-zendframework-bridge','1.8.0','1.8.0','up-to-date','Alias legacy ZF class names to Laminas Project equivalents.',1,368),
(205,'masterminds/html5','2.9.0','2.10.0','semver-safe-update','An HTML5 parser and serializer.',1,369),
(206,'mustache/mustache','2.14.2','3.0.0','update-possible','A Mustache implementation in PHP.',1,372),
(207,'myclabs/deep-copy','1.13.0','1.13.4','semver-safe-update','Create deep copies (clones) of your objects',1,373),
(208,'nikic/php-parser','5.4.0','5.6.2','semver-safe-update','A PHP parser written in PHP',1,374),
(209,'phpdocumentor/reflection-docblock','5.6.2','5.6.3','semver-safe-update','With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.',1,379),
(210,'phplucidframe/console-table','1.3.1','1.4.0','semver-safe-update','Console Table',1,381),
(211,'phpspec/prophecy','1.20.0','1.22.0','semver-safe-update','Highly opinionated mocking framework for PHP 5.3+',1,382),
(212,'phpstan/phpdoc-parser','2.1.0','2.3.0','semver-safe-update','PHPDoc parser with support for nullable, intersection and generic types',1,383),
(213,'phpunit/phpunit','10.5.45','10.5.58','semver-safe-update','The PHP Unit Testing framework.',1,389),
(214,'psr/cache','1.0.1','3.0.0','update-possible','Common interface for caching libraries',1,390),
(215,'psr/container','1.1.2','2.0.2','update-possible','Common Container Interface (PHP FIG PSR-11)',1,392),
(216,'psr/simple-cache','1.0.1','3.0.0','update-possible','Common interfaces for simple caching',1,398),
(217,'ramsey/uuid','4.7.6','4.9.1','semver-safe-update','A PHP library for generating and working with universally unique identifiers (UUIDs).',1,401),
(218,'ramsey/uuid-doctrine','1.8.2','2.1.0','update-possible','Use ramsey/uuid as a Doctrine field type.',1,402),
(219,'sebastian/comparator','5.0.3','5.0.4','semver-safe-update','Provides the functionality to compare PHP values for equality',1,408),
(220,'sebastian/exporter','5.1.2','5.1.4','semver-safe-update','Provides the functionality to export PHP variables for visualization',1,412),
(221,'sebastian/recursion-context','5.0.0','5.0.1','semver-safe-update','Provides functionality to recursively process PHP variables',1,417),
(222,'slevomat/coding-standard','8.18.0','8.24.0','semver-safe-update','Slevomat Coding Standard for PHP_CodeSniffer complements Consistence Coding Standard by providing sniffs with additional checks.',1,421),
(223,'squizlabs/php_codesniffer','3.12.2','4.0.0','update-possible','PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.',1,422),
(224,'swiftmailer/swiftmailer','6.3.0','6.3.0','up-to-date','Swiftmailer, free feature-rich PHP mailer',1,423),
(225,'symfony/cache','5.4.46','6.4.27','update-possible','Provides extended PSR-6, PSR-16 (and tags) implementations',1,424),
(226,'symfony/cache-contracts','2.5.4','3.6.0','update-possible','Generic abstractions related to caching',1,425),
(227,'symfony/console','6.4.20','6.4.27','semver-safe-update','Eases the creation of beautiful and testable command line interfaces',1,426),
(228,'symfony/css-selector','6.4.13','6.4.24','semver-safe-update','Converts CSS selectors to XPath expressions',1,427),
(229,'symfony/deprecation-contracts','3.5.1','3.6.0','semver-safe-update','A generic function and convention to trigger deprecation notices',1,428),
(230,'symfony/dom-crawler','6.4.19','6.4.25','semver-safe-update','Eases DOM navigation for HTML and XML documents',1,429),
(231,'symfony/event-dispatcher','6.4.13','6.4.25','semver-safe-update','Provides tools that allow your application components to communicate with each other by dispatching events and listening to them',1,430),
(232,'symfony/event-dispatcher-contracts','3.5.1','3.6.0','semver-safe-update','Generic abstractions related to dispatching event',1,431),
(233,'symfony/filesystem','6.4.13','6.4.24','semver-safe-update','Provides basic utilities for the filesystem',1,432),
(234,'symfony/polyfill-ctype','1.31.0','1.33.0','semver-safe-update','Symfony polyfill for ctype functions',1,433),
(235,'symfony/polyfill-iconv','1.31.0','1.33.0','semver-safe-update','Symfony polyfill for the Iconv extension',1,434),
(236,'symfony/polyfill-intl-grapheme','1.31.0','1.33.0','semver-safe-update','Symfony polyfill for intl\'s grapheme_* functions',1,435),
(237,'symfony/polyfill-intl-idn','1.31.0','1.33.0','semver-safe-update','Symfony polyfill for intl\'s idn_to_ascii and idn_to_utf8 functions',1,436),
(238,'symfony/polyfill-intl-normalizer','1.31.0','1.33.0','semver-safe-update','Symfony polyfill for intl\'s Normalizer class and related functions',1,437),
(239,'symfony/polyfill-mbstring','1.31.0','1.33.0','semver-safe-update','Symfony polyfill for the Mbstring extension',1,438),
(240,'symfony/polyfill-php73','1.31.0','1.33.0','semver-safe-update','Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions',1,440),
(241,'symfony/polyfill-php80','1.31.0','1.33.0','semver-safe-update','Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions',1,441),
(242,'symfony/polyfill-php81','1.31.0','1.33.0','semver-safe-update','Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions',1,442),
(243,'symfony/polyfill-php84','1.31.0','1.33.0','semver-safe-update','Symfony polyfill backporting some PHP 8.4+ features to lower PHP versions',1,443),
(244,'symfony/process','6.4.20','6.4.26','semver-safe-update','Executes commands in sub-processes',1,444),
(245,'symfony/service-contracts','3.5.1','3.6.0','semver-safe-update','Generic abstractions related to writing services',1,445),
(246,'symfony/stopwatch','6.4.19','6.4.24','semver-safe-update','Provides a way to profile code',1,446),
(247,'symfony/string','6.4.15','6.4.26','semver-safe-update','Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way',1,447),
(248,'symfony/var-dumper','6.4.18','6.4.26','semver-safe-update','Provides mechanisms for walking through any arbitrary PHP variable',1,448),
(249,'symfony/var-exporter','6.4.20','6.4.26','semver-safe-update','Allows exporting any serializable PHP data structure to plain PHP code',1,449),
(250,'webmozart/assert','1.11.0','1.12.0','semver-safe-update','Assertions to validate method input/output with nice error messages.',1,453),
(251,'wirklich-digital/cron-scheduler','1.6','2.2.1','update-possible','Cron Scheduling Module',1,496),
(252,'wirklich-digital/data-tables','2.4.4','2.4.5','semver-safe-update','Server-Side processor for DataTables',1,497),
(253,'wirklich-digital/dynamic-entity-translatable-module','1.1','1.1.1','semver-safe-update','Translatable extension for Dynamic Entity Module',1,508),
(254,'wirklich-digital/election-theme','1.7.2','1.7.3','semver-safe-update','ElectionTheme',1,509),
(255,'wirklich-digital/entity-translation-locale-route','1.1','1.1.1','semver-safe-update','EntityTranslationLocaleRoute',1,512),
(256,'wirklich-digital/git-package-tools','1.1','1.2','semver-safe-update','Simple tools for creating git repositories from modules',1,520),
(257,'wirklich-digital/laminas-syshelper-client','2.1.1','2.1.2','semver-safe-update','LaminasSyshelperClient',1,527),
(258,'wirklich-digital/messagehub-connector','1.2.2','2.3','update-possible','This package connects to the MessageHub system. Classes will be available for easy usage.',1,533),
(259,'wirklich-digital/php-cli','1.1.2','1.2.4','semver-safe-update','PhpCli',1,541),
(260,'wirklich-digital/stdlib','1.4','1.5.3','semver-safe-update','Wirklich.Digital Standard-Bibliothek',1,552),
(261,'wirklich-digital/swiftmailer-messenger','1.3','1.4','semver-safe-update','SwiftmailerMessenger',1,554),
(262,'behat/transliterator','1.5.0','1.5.0','up-to-date','String transliterator',2,286),
(263,'brick/varexporter','0.5.0','0.6.0','update-possible','A powerful alternative to var_export(), which can export closures and objects without __set_state()',2,288),
(264,'doctrine/annotations','2.0.2','2.0.2','up-to-date','Docblock Annotations Parser',2,298),
(265,'doctrine/cache','2.2.0','2.2.0','up-to-date','PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.',2,299),
(266,'doctrine/dbal','3.10.2','4.2.5','update-possible','Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.',2,302),
(267,'doctrine/lexer','2.1.1','3.0.1','update-possible','PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.',2,310),
(268,'doctrine/orm','2.20.6','3.5.3','update-possible','Object-Relational-Mapper for PHP',2,312),
(269,'doctrine/persistence','3.4.0','4.1.1','update-possible','The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.',2,313),
(270,'egulias/email-validator','3.2.6','4.0.4','update-possible','A library for validating emails against several RFCs',2,315),
(271,'ezyang/htmlpurifier','4.18.0','4.19.0','semver-safe-update','Standards compliant HTML filter written in PHP',2,316),
(272,'gedmo/doctrine-extensions','3.20.0','3.21.0','semver-safe-update','Doctrine behavioral extensions',2,318),
(273,'kint-php/kint','5.1.1','6.0.1','update-possible','Kint - debugging tool for PHP developers',2,322),
(274,'laminas/laminas-cache','3.13.0','4.1.0','update-possible','Caching implementation with a variety of storage options, as well as codified caching strategies for callbacks, classes, and output',2,324),
(275,'laminas/laminas-cache-storage-adapter-filesystem','2.5.0','3.1.0','update-possible','Laminas cache adapter for filesystem',2,325),
(276,'laminas/laminas-cache-storage-adapter-memory','2.4.0','3.1.0','update-possible','Laminas cache adapter for memory',2,326),
(277,'laminas/laminas-component-installer','3.5.0','3.6.0','semver-safe-update','Composer plugin for injecting modules and configuration providers into application configuration',2,330),
(278,'laminas/laminas-config','3.10.1','3.10.1','up-to-date','provides a nested object property based user interface for accessing this configuration data within application code',2,331),
(279,'laminas/laminas-filter','2.41.0','3.2.1','update-possible','Programmatically filter and normalize data and files',2,338),
(280,'laminas/laminas-inputfilter','2.33.0','2.33.1','semver-safe-update','Normalize and validate input sets from the web, APIs, the CLI, and more, including files',2,344),
(281,'laminas/laminas-json','3.7.1','3.7.1','up-to-date','provides convenience methods for serializing native PHP to JSON and decoding JSON to native PHP',2,345),
(282,'laminas/laminas-loader','2.11.1','2.11.1','up-to-date','Autoloading and plugin loading strategies',2,346),
(283,'laminas/laminas-mail','2.25.1','2.25.1','up-to-date','Provides generalized functionality to compose and send both text and MIME-compliant multipart e-mail messages',2,347),
(284,'laminas/laminas-mime','2.12.0','2.12.0','up-to-date','Create and parse MIME messages and parts',2,348),
(285,'laminas/laminas-modulemanager','2.17.0','2.18.0','semver-safe-update','Modular application system for laminas-mvc applications',2,349),
(286,'laminas/laminas-navigation','2.20.0','2.21.0','semver-safe-update','Manage trees of pointers to web pages in order to build navigation systems',2,354),
(287,'laminas/laminas-paginator','2.19.0','2.20.0','semver-safe-update','Paginate collections of data from arbitrary sources',2,355),
(288,'laminas/laminas-serializer','2.18.0','3.1.0','update-possible','Serialize and deserialize PHP structures to a variety of representations',2,358),
(289,'laminas/laminas-servicemanager','3.23.1','4.4.0','update-possible','Factory-Driven Dependency Injection Container',2,359),
(290,'laminas/laminas-session','2.24.0','2.25.1','semver-safe-update','Object-oriented interface to PHP sessions and storage',2,360),
(291,'laminas/laminas-text','2.12.1','2.12.1','up-to-date','Create FIGlets and text-based tables',2,363),
(292,'laminas/laminas-validator','2.64.4','3.8.0','update-possible','Validation classes for a wide range of domains, and the ability to chain validators to create complex validation criteria',2,366),
(293,'laminas/laminas-view','2.41.0','2.43.0','semver-safe-update','Flexible view layer supporting and providing multiple view layers, helpers, and more',2,367),
(294,'laminas/laminas-zendframework-bridge','1.8.0','1.8.0','up-to-date','Alias legacy ZF class names to Laminas Project equivalents.',2,368),
(295,'mustache/mustache','2.14.2','3.0.0','update-possible','A Mustache implementation in PHP.',2,372),
(296,'phpunit/phpunit','10.5.53','10.5.58','semver-safe-update','The PHP Unit Testing framework.',2,389),
(297,'psr/cache','1.0.1','3.0.0','update-possible','Common interface for caching libraries',2,390),
(298,'psr/container','1.1.2','2.0.2','update-possible','Common Container Interface (PHP FIG PSR-11)',2,392),
(299,'psr/simple-cache','1.0.1','3.0.0','update-possible','Common interfaces for simple caching',2,398),
(300,'ramsey/uuid-doctrine','1.8.2','2.1.0','update-possible','Use ramsey/uuid as a Doctrine field type.',2,402),
(301,'sebastian/comparator','5.0.3','5.0.4','semver-safe-update','Provides the functionality to compare PHP values for equality',2,408),
(302,'sebastian/exporter','5.1.2','5.1.4','semver-safe-update','Provides the functionality to export PHP variables for visualization',2,412),
(303,'slevomat/coding-standard','8.22.1','8.24.0','semver-safe-update','Slevomat Coding Standard for PHP_CodeSniffer complements Consistence Coding Standard by providing sniffs with additional checks.',2,421),
(304,'squizlabs/php_codesniffer','3.13.4','4.0.0','update-possible','PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.',2,422),
(305,'swiftmailer/swiftmailer','6.3.0','6.3.0','up-to-date','Swiftmailer, free feature-rich PHP mailer',2,423),
(306,'symfony/cache','5.4.46','6.4.27','update-possible','Provides extended PSR-6, PSR-16 (and tags) implementations',2,424),
(307,'symfony/cache-contracts','2.5.4','3.6.0','update-possible','Generic abstractions related to caching',2,425),
(308,'symfony/console','6.4.25','6.4.27','semver-safe-update','Eases the creation of beautiful and testable command line interfaces',2,426),
(309,'symfony/process','6.4.25','6.4.26','semver-safe-update','Executes commands in sub-processes',2,444),
(310,'symfony/string','6.4.25','6.4.26','semver-safe-update','Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way',2,447),
(311,'symfony/var-dumper','6.4.25','6.4.26','semver-safe-update','Provides mechanisms for walking through any arbitrary PHP variable',2,448),
(312,'symfony/var-exporter','6.4.25','6.4.26','semver-safe-update','Allows exporting any serializable PHP data structure to plain PHP code',2,449),
(313,'webmozart/assert','1.11.0','1.12.0','semver-safe-update','Assertions to validate method input/output with nice error messages.',2,453),
(314,'wirklich-digital/admin-authorization','2.3.1','2.5.1','semver-safe-update','Adminisration interface for wirklich-digital/authorization',2,456),
(315,'wirklich-digital/cron-scheduler','1.6','2.2.1','update-possible','Cron Scheduling Module',2,496),
(316,'wirklich-digital/entity-translation','2.2.2','4.0.1','update-possible','EntityTranslation',2,511),
(317,'wirklich-digital/locale-route','1.2.4','2.0.1','update-possible','LocaleRoute',2,529),
(318,'wirklich-digital/messagehub-connector','1.2.2','2.3','update-possible','This package connects to the MessageHub system. Classes will be available for easy usage.',2,533),
(319,'wirklich-digital/stdlib','1.5.2','1.5.3','semver-safe-update','Wirklich.Digital Standard-Bibliothek',2,552),
(320,'wirklich-digital/system-translation','2.1.1','3.0.5','update-possible','SystemTranslation',2,556),
(321,'nikic/php-parser','5.6.1','5.6.2','semver-safe-update','A PHP parser written in PHP',2,374),
(322,'doctrine/collections','2.3.0','2.4.0','semver-safe-update','PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.',2,300),
(323,'doctrine/collections','2.3.0','2.4.0','semver-safe-update','PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.',1,300),
(324,'friendsofphp/proxy-manager-lts','1.0.18','1.0.19','semver-safe-update','Adding support for a wider range of PHP versions to ocramius/proxy-manager',2,317),
(325,'friendsofphp/proxy-manager-lts','1.0.18','1.0.19','semver-safe-update','Adding support for a wider range of PHP versions to ocramius/proxy-manager',1,317);
/*!40000 ALTER TABLE `LaminasSystemServerComposerOutdated` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;

