<h1><?= $this->translate('IP Subnets'); ?></h1>

<div class="uk-grid">
    <div class="uk-width-medium-1-1  uk-grid-margin">
        <div class="md-card">
            <div class="md-card-toolbar">
                <h3 class="md-card-toolbar-heading-text"><?= $this->translate('Subnet list'); ?></h3>
            </div>
            <div class="md-card-content">
    
    <?= $this->datatable()
             ->setTableClasses(['dataTable', 'uk-table'])
             ->render($this->datatable); ?>
    </div>
        </div>
    </div>
</div>

<script>
    window.wirklichDigitalDataTableCurrentConfig = {
        processing: true,
        serverSide: true,
        ajax: <?= json_encode($this->url('syshelper-frontend/ip-subnet/listAjax')) ?>,
        order: [[ 0, 'asc' ]],
        columnDefs: <?= $this->datatableColumnDefinition($this->datatable, []); ?>,
        language: <?= $this->datatableLanguageDefinition(); ?>,
    };
</script>